[package]
name = "rusthesia"
version = "0.1.5"
authors = ["Jochen Kiemes <jochen@kiemes.de>"]
edition = "2018"
license = "MIT"
description = "Reads midi files and create piano notes waterfall."
homepage = "https://github.com/gin66/rusthesia"
repository = "https://github.com/gin66/rusthesia"
keywords = ["music", "midi", "piano", "learning", "sdl2"]
readme = "README.md"

[dependencies]
log = "0.4"
simple-logging = "2.0"
midir = "0.5"
midly = "0.1"
sdl2-unifont = "1.0"
clap = "2.32"
indoc = "0.3"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["gfx"]
